---
- hosts: all
  become: yes
  tasks:
  - name: install git,tree and wget on all nodes using loops
    apt:
     name: "{{ item }}"
     state: present
    with_items:
     - git
     - tree
     - wget
